// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKAf6I72HVGtGW_p95g9KHY1Nza4GOLCs',
    appId: '1:393281347446:web:9d8b03f4ed5b4d543ba457',
    messagingSenderId: '393281347446',
    projectId: 'petdiary-21b82',
    authDomain: 'petdiary-21b82.firebaseapp.com',
    storageBucket: 'petdiary-21b82.appspot.com',
    measurementId: 'G-Z4C1ZH0G1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHi9a02FnzQaHKBHnLEYItH0XV9rkD42Y',
    appId: '1:393281347446:android:c39d065f7e787e8c3ba457',
    messagingSenderId: '393281347446',
    projectId: 'petdiary-21b82',
    storageBucket: 'petdiary-21b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJifI3LcfVmquc_7agw1CGo5dlFW4A3xo',
    appId: '1:393281347446:ios:7bb2857472486afa3ba457',
    messagingSenderId: '393281347446',
    projectId: 'petdiary-21b82',
    storageBucket: 'petdiary-21b82.appspot.com',
    iosClientId: '393281347446-3h6dqbpag4iqq6b4488rj9bu6p1hfuc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.petdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJifI3LcfVmquc_7agw1CGo5dlFW4A3xo',
    appId: '1:393281347446:ios:7bb2857472486afa3ba457',
    messagingSenderId: '393281347446',
    projectId: 'petdiary-21b82',
    storageBucket: 'petdiary-21b82.appspot.com',
    iosClientId: '393281347446-3h6dqbpag4iqq6b4488rj9bu6p1hfuc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.petdiary',
  );
}
